# Generated by Django 5.2.6 on 2025-10-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Talla', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha_Fabricacion', models.DateField()),
            ],
        ),
    ]
