"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

# ==========================
# RUTAS BÁSICAS DEL PROYECTO
# ==========================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# CONFIGURACIÓN GENERAL
# ==========================

SECRET_KEY = 'django-insecure-)&@k#tu3_2y+(o$4vu#4*o*uklvi4!)7#5kj6d#x^indzac&7s'

DEBUG = True

ALLOWED_HOSTS = []


# ==========================
# APLICACIONES INSTALADAS
# ==========================

INSTALLED_APPS = [
    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps de terceros
    'rest_framework',
    'corsheaders',

    # Tu app
    'api',
]


# ==========================
# MIDDLEWARE
# ==========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',     # 👈 obligatorio arriba del CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================
# CONFIGURACIÓN DE URLS Y WSGI
# ==========================

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# ==========================
# BASE DE DATOS
# ==========================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==========================
# VALIDACIÓN DE CONTRASEÑAS
# ==========================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==========================
# CONFIGURACIÓN REGIONAL
# ==========================

LANGUAGE_CODE = 'es-co'  # Español Colombia
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# ==========================
# ARCHIVOS ESTÁTICOS
# ==========================

STATIC_URL = 'static/'


# ==========================
# CLAVE POR DEFECTO
# ==========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================
# CONFIGURACIÓN EXTRA (CORS + REST FRAMEWORK)
# ==========================

# Permitir acceso desde frontend local
CORS_ALLOW_ALL_ORIGINS = True   # ✔ para desarrollo

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
]


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}
