# Generated by Django 5.2.6 on 2025-11-07 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='numero_clase',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='clase',
            name='deporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='diametro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.date(2025, 11, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='deporte',
            field=models.CharField(default='Fútbol', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='diametro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 11, 7), verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=50),
            preserve_default=False,
        ),
    ]
