# Generated by Django 5.2.6 on 2025-10-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_fabricacion', models.DateField()),
            ],
        ),
    ]
